// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaiwanStockExchangeData.Data;

namespace TaiwanStockExchangeData.Migrations
{
    [DbContext(typeof(TaiwanStockExchangeDataContext))]
    [Migration("20210406073205_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TaiwanStockExchangeData.Models.Security", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("DividendYear")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DividendYield")
                        .HasColumnType("REAL");

                    b.Property<string>("FinancialStatements")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("PriceToBookRatio")
                        .HasColumnType("REAL");

                    b.Property<double>("PriceToEarningRatio")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Security");
                });
#pragma warning restore 612, 618
        }
    }
}
