// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaiwanStockExchangeData.Data;

namespace TaiwanStockExchangeData.Migrations
{
    [DbContext(typeof(TaiwanStockExchangeDataContext))]
    partial class TaiwanStockExchangeDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("TaiwanStockExchangeData.Models.Security", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<long>("DividendYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DividendYield")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("FinancialStatements")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceToBookRatio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("PriceToEarningRatio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ID");

                    b.ToTable("Security");
                });
#pragma warning restore 612, 618
        }
    }
}
